export default {
    FETCH_WEEK_FORECAST_REQUEST: 'FETCH_WEEK_FORECAST_REQUEST',
    FETCH_WEEK_FORECAST_SUCCESS: 'FETCH_WEEK_FORECAST_SUCCESS',
    FETCH_WEEK_FORECAST_ERROR: 'FETCH_WEEK_FORECAST_ERROR',
    FETCH_DAY_FORECAST_REQUEST: 'FETCH_DAY_FORECAST_REQUEST',
    FETCH_DAY_FORECAST_SUCCESS: 'FETCH_DAY_FORECAST_SUCCESS',
    FETCH_DAY_FORECAST_ERROR: 'FETCH_DAY_FORECAST_ERROR'
};